#!/usr/bin/env bash
python pre_process.py -image photos/real5.png && \
python ctc_predict.py -image ./output/staffs/cropped0.png -model Models/papers_agnostic_model/agnostic_model.meta -vocabulary vocabulary_442.txt
